/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

/**
 *
 * @author Estudiante
 */
public class AdministradorPrincipal extends javax.swing.JPanel {
    
    private GestionarOperadores gestionarOperadores = new GestionarOperadores();
    private GenerarInforme generarInforme = new GenerarInforme();
    private Estadisticas estadisticas = new Estadisticas();

    /**
     * Creates new form AdministradorPrincipal
     */
    public AdministradorPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BienvenidoAdministradorL = new javax.swing.JLabel();
        CerrarSesionAdministradorB = new javax.swing.JButton();
        VerEstadisticasB = new javax.swing.JButton();
        GenerarInformesB = new javax.swing.JButton();
        GestionarOperadoresB = new javax.swing.JButton();

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        BienvenidoAdministradorL.setText("Administrador");

        CerrarSesionAdministradorB.setText("Cerrar Sesión");
        CerrarSesionAdministradorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionAdministradorBActionPerformed(evt);
            }
        });

        VerEstadisticasB.setText("Ver Estadísticas");
        VerEstadisticasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEstadisticasBActionPerformed(evt);
            }
        });

        GenerarInformesB.setText("Generar Informes");
        GenerarInformesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarInformesBActionPerformed(evt);
            }
        });

        GestionarOperadoresB.setText("Gestionar Operadores");
        GestionarOperadoresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarOperadoresBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(GestionarOperadoresB)
                        .addComponent(GenerarInformesB)
                        .addComponent(VerEstadisticasB)
                        .addComponent(CerrarSesionAdministradorB)
                        .addComponent(BienvenidoAdministradorL))
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BienvenidoAdministradorL)
                    .addGap(33, 33, 33)
                    .addComponent(GestionarOperadoresB)
                    .addGap(37, 37, 37)
                    .addComponent(GenerarInformesB)
                    .addGap(35, 35, 35)
                    .addComponent(VerEstadisticasB)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                    .addComponent(CerrarSesionAdministradorB)
                    .addContainerGap()))
        );

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GestionarOperadoresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarOperadoresBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(gestionarOperadores);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_GestionarOperadoresBActionPerformed

    private void GenerarInformesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarInformesBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(generarInforme);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_GenerarInformesBActionPerformed

    private void VerEstadisticasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEstadisticasBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(estadisticas);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_VerEstadisticasBActionPerformed

    private void CerrarSesionAdministradorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionAdministradorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesionAdministradorBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidoAdministradorL;
    private javax.swing.JButton CerrarSesionAdministradorB;
    private javax.swing.JButton GenerarInformesB;
    private javax.swing.JButton GestionarOperadoresB;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton VerEstadisticasB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
