/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

/**
 *
 * @author Estudiante
 */
public class CrearOperador extends javax.swing.JPanel {

    /**
     * Creates new form CrearOperador
     */
    public CrearOperador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ValidarContraseaOperadorTF = new javax.swing.JPasswordField();
        ContrasenaCrearOperadorTF = new javax.swing.JPasswordField();
        CrearOperarioB = new javax.swing.JButton();
        AtrasB = new javax.swing.JButton();
        UsuarioCrearOperadorTF = new javax.swing.JTextField();
        ValidarContraseaOperadorL = new javax.swing.JLabel();
        ContrasenaCrearOperadorL = new javax.swing.JLabel();
        UsuarioCrearOperadorL = new javax.swing.JLabel();
        DatosOperadorL = new javax.swing.JLabel();

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        CrearOperarioB.setText("Crear ►");
        CrearOperarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearOperarioBActionPerformed(evt);
            }
        });

        AtrasB.setText("◄ Atrás");
        AtrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBActionPerformed(evt);
            }
        });

        UsuarioCrearOperadorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCrearOperadorTFActionPerformed(evt);
            }
        });

        ValidarContraseaOperadorL.setText("Validar contraseña:");

        ContrasenaCrearOperadorL.setText("Contraseña:");

        UsuarioCrearOperadorL.setText("Nombre de usuario:");

        DatosOperadorL.setText("Por favor suministre todos los datos requeridos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(AtrasB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CrearOperarioB))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(UsuarioCrearOperadorL)
                                    .addGap(79, 79, 79)
                                    .addComponent(UsuarioCrearOperadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ContrasenaCrearOperadorL)
                                        .addComponent(ValidarContraseaOperadorL))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(80, 80, 80)
                                            .addComponent(ContrasenaCrearOperadorTF))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ValidarContraseaOperadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(55, 55, 55))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(DatosOperadorL)
                            .addGap(81, 81, 81)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(DatosOperadorL)
                    .addGap(46, 46, 46)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UsuarioCrearOperadorL)
                        .addComponent(UsuarioCrearOperadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ContrasenaCrearOperadorL)
                        .addComponent(ContrasenaCrearOperadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ValidarContraseaOperadorL)
                        .addComponent(ValidarContraseaOperadorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AtrasB)
                        .addComponent(CrearOperarioB))
                    .addGap(16, 16, 16)))
        );

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioCrearOperadorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCrearOperadorTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioCrearOperadorTFActionPerformed

    private void CrearOperarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearOperarioBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearOperarioBActionPerformed

    private void AtrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasB;
    private javax.swing.JLabel ContrasenaCrearOperadorL;
    private javax.swing.JPasswordField ContrasenaCrearOperadorTF;
    private javax.swing.JButton CrearOperarioB;
    private javax.swing.JLabel DatosOperadorL;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel UsuarioCrearOperadorL;
    private javax.swing.JTextField UsuarioCrearOperadorTF;
    private javax.swing.JLabel ValidarContraseaOperadorL;
    private javax.swing.JPasswordField ValidarContraseaOperadorTF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
