/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

import ENTIDAD.Administrador;
import ENTIDAD.Sistema;
import java.util.ArrayList;

/**
 *
 * @author Estudiante
 */
public class FramePrincipal extends javax.swing.JFrame {

    public static InicioAdministrador inicioAdministrador = new InicioAdministrador();
    private IniciarSesionOperario iniciarSesionOperario = new IniciarSesionOperario();

    /**
     * Creates new form FramePrincipal
     */
    public static Sistema sistema = new Sistema();

    public FramePrincipal() {
        initComponents();
        //inicializacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AdministradorB = new javax.swing.JButton();
        OperarioB = new javax.swing.JButton();
        BienvenidoL = new javax.swing.JLabel();
        RolL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS Parqueadero");

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        AdministradorB.setText("Administrador");
        AdministradorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministradorBActionPerformed(evt);
            }
        });

        OperarioB.setText("Operario");
        OperarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperarioBActionPerformed(evt);
            }
        });

        BienvenidoL.setText("Bienvenido");

        RolL.setText("Por favor seleccione su rol");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RolL)
                    .addComponent(BienvenidoL)
                    .addComponent(AdministradorB)
                    .addComponent(OperarioB))
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BienvenidoL)
                .addGap(18, 18, 18)
                .addComponent(RolL)
                .addGap(31, 31, 31)
                .addComponent(AdministradorB)
                .addGap(33, 33, 33)
                .addComponent(OperarioB)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        PanelPrincipal.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperarioBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(iniciarSesionOperario);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_OperarioBActionPerformed

    private void AdministradorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministradorBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(inicioAdministrador);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_AdministradorBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    public void inicializacion() {
        /*
        Administrador daniel = new Administrador("daniel", "1234");
        sistema.setAdministrador(daniel);
        for (Administrador u : sistema.getAdministrador()) {
            System.out.println(u.getUsuarioAdministrador());
            System.out.println(u.getContraseñaAdministrador());
            System.out.println("------------");
        }
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministradorB;
    private javax.swing.JLabel BienvenidoL;
    private javax.swing.JButton OperarioB;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel RolL;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
