/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

/**
 *
 * @author danyy
 */
public class GenerarInforme extends javax.swing.JPanel {

    /**
     * Creates new form GenerarInforma
     */
    public GenerarInforme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AtrasB = new javax.swing.JButton();
        PuntosRedimidosB = new javax.swing.JButton();
        InformeClientesB = new javax.swing.JButton();
        InformesL = new javax.swing.JLabel();

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        AtrasB.setText("◄ Atrás");
        AtrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBActionPerformed(evt);
            }
        });

        PuntosRedimidosB.setText("Puntos Redimidos");
        PuntosRedimidosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntosRedimidosBActionPerformed(evt);
            }
        });

        InformeClientesB.setText("Registro de Clientes");
        InformeClientesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeClientesBActionPerformed(evt);
            }
        });

        InformesL.setText("Seleccione el informe que desea generar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AtrasB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(InformeClientesB)
                            .addComponent(PuntosRedimidosB)
                            .addComponent(InformesL))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformesL)
                .addGap(37, 37, 37)
                .addComponent(InformeClientesB)
                .addGap(37, 37, 37)
                .addComponent(PuntosRedimidosB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(AtrasB)
                .addContainerGap())
        );

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InformeClientesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeClientesBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeClientesBActionPerformed

    private void PuntosRedimidosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntosRedimidosBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntosRedimidosBActionPerformed

    private void AtrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasB;
    private javax.swing.JButton InformeClientesB;
    private javax.swing.JLabel InformesL;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton PuntosRedimidosB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
