/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTERA;

/**
 *
 * @author Estudiante
 */
public class GestionarOperadores extends javax.swing.JPanel {
    
    private CrearOperador crearOperador = new CrearOperador();
    private EliminarOperador eliminarOperador = new EliminarOperador();
    private ModificarOperador modificarOperador = new ModificarOperador();

    /**
     * Creates new form GestionarOperadores
     */
    public GestionarOperadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AtrasB = new javax.swing.JButton();
        ModificarOperadoresB = new javax.swing.JButton();
        EliminarOperadorB = new javax.swing.JButton();
        CrearOperadorB = new javax.swing.JButton();
        SeleccioneElProcesoOperarioL = new javax.swing.JLabel();

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        AtrasB.setText("◄ Atrás");
        AtrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBActionPerformed(evt);
            }
        });

        ModificarOperadoresB.setText("Modificar Operadores");
        ModificarOperadoresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarOperadoresBActionPerformed(evt);
            }
        });

        EliminarOperadorB.setText("Eliminar Operador");
        EliminarOperadorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarOperadorBActionPerformed(evt);
            }
        });

        CrearOperadorB.setText("Crear Operador");
        CrearOperadorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearOperadorBActionPerformed(evt);
            }
        });

        SeleccioneElProcesoOperarioL.setText("Seleccione el proceso a realizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(CrearOperadorB)
                            .addComponent(SeleccioneElProcesoOperarioL)
                            .addComponent(EliminarOperadorB)
                            .addComponent(ModificarOperadoresB)))
                    .addComponent(AtrasB))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeleccioneElProcesoOperarioL)
                .addGap(30, 30, 30)
                .addComponent(CrearOperadorB)
                .addGap(33, 33, 33)
                .addComponent(EliminarOperadorB)
                .addGap(33, 33, 33)
                .addComponent(ModificarOperadoresB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(AtrasB)
                .addContainerGap())
        );

        PanelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearOperadorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearOperadorBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(crearOperador);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_CrearOperadorBActionPerformed

    private void EliminarOperadorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarOperadorBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(eliminarOperador);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_EliminarOperadorBActionPerformed

    private void ModificarOperadoresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarOperadoresBActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.setVisible(false);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(modificarOperador);
        PanelPrincipal.setVisible(true);
    }//GEN-LAST:event_ModificarOperadoresBActionPerformed

    private void AtrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasB;
    private javax.swing.JButton CrearOperadorB;
    private javax.swing.JButton EliminarOperadorB;
    private javax.swing.JButton ModificarOperadoresB;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel SeleccioneElProcesoOperarioL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
